In [1]:
# Import Libraries
import pandas as pd
import numpy as np  # used for future calculations

In [17]:
fake = pd.read_csv('data/Fake.csv')
true = pd.read_csv('data/True.csv')

print("Fake news shape:", fake.shape)
print("True news shape:", true.shape)

Fake news shape: (23481, 4)
True news shape: (21417, 4)

In [18]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [19]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [20]:
# Add label 0 to fake news
fake['label'] = 0

# Add label 1 to true news
true['label'] = 1

print("Labels added!")

Labels added!

In [21]:
# Combine both dataframes into one
df = pd.concat([fake, true], ignore_index=True)

print("Total rows:", len(df))
print("Columns:", df.columns.tolist())

Total rows: 44898
Columns: ['title', 'text', 'subject', 'date', 'label']

In [22]:
# Shuffle the data so fake and real news are mixed
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
print("Data shuffled!")
print(df.head())

Data shuffled!
                                               title  \
0  Ben Stein Calls Out 9th Circuit Court: Committ...
1  Trump drops Steve Bannon from National Securit...
2  Puerto Rico expects U.S. to lift Jones Act shi...
3   OOPS: Trump Just Accidentally Confirmed He Le...
4  Donald Trump heads for Scotland to reopen a go...

                                                text       subject  \
0  21st Century Wire says Ben Stein, reputable pr...       US_News
1  WASHINGTON (Reuters) - U.S. President Donald T...  politicsNews
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...  politicsNews
3  On Monday, Donald Trump once again embarrassed...          News
4  GLASGOW, Scotland (Reuters) - Most U.S. presid...  politicsNews

                  date  label
0    February 13, 2017      0
1       April 5, 2017       1
2  September 27, 2017       1
3         May 22, 2017      0
4       June 24, 2016       1

In [23]:
# Check basic info of dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 112.3 MB

In [24]:
# Check fake vs real news count
print("Fake vs Real News Count:")
print(df['label'].value_counts())
print("\n0 = Fake News")
print("1 = Real News")

Fake vs Real News Count:
label
0    23481
1    21417
Name: count, dtype: int64

0 = Fake News
1 = Real News

In [25]:
# Check missing values
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [26]:
# Check subject categories
print("Fake News Subjects:")
print(fake['subject'].value_counts())
print("\nTrue News Subjects:")
print(true['subject'].value_counts())

Fake News Subjects:
subject
News               9050
politics           6841
left-news          4459
Government News    1570
US_News             783
Middle-east         778
Name: count, dtype: int64

True News Subjects:
subject
politicsNews    11272
worldnews       10145
Name: count, dtype: int64

In [27]:
# Save cleaned dataset
df.to_csv('data/fake_news_cleaned.csv', index=False)
print("Dataset saved successfully!")

Dataset saved successfully!

In [28]:
# Check average text length of fake vs real news
df['text_length'] = df['text'].apply(len)

print("Average text length:")
print(df.groupby('label')['text_length'].mean())
print("\n0 = Fake News, 1 = Real News")

Average text length:
label
0    2547.396235
1    2383.278517
Name: text_length, dtype: float64

0 = Fake News, 1 = Real News